package uk.gov.moj.cpp.staging.pubhub.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.staging.pubhub.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - stagingpubhub.command.publish-standard-list"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingpubhub.command.publish-standard-list");
      then
        $outcome.setSuccess(true);
    end
